### ISSUE TITLE
Closed Captions on IE10

### ISSUE THREAD

**Issue by naeem91** [ooyala/html5-video-plugins#261]
Closed captions does not work on IE10 using main_html5.js. Although IE10 is said to have support for `<track>` tag and WebVTT.

**Comment by mityaha** [comment]
Can you please provide us URLs of the asset and CC track you are seeing the problem with?

**Comment by mityaha** [comment]
And actually, we don't support IE10, we support IE11+ and Edge on Windows.

**Comment by naeem91** [comment]
This is the ooyala content id `VtZWc4ODE61SNu7RdCJTlDhHLJ23vl5d` which has multiple CC attached. 

These get embedded correctly in `<video>`  as `<track>` tags but are not displayed. Because [IE10 says it support CC](https://msdn.microsoft.com/en-us/library/hh772556(v=vs.85).aspx) so I wanted to see if there's any possible fix for the issue.

**Comment by mityaha** [comment]
As you can see, CC code for main_html5.js is very platform/browser dependent, supporting IE10 will make it even more complex.  Sorry about that.
